swagger: "2.0"
info:
  version: "0.0.1"
  description: "Manage SWC files in the SWC database"
  title: SWC File API
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /tracings:
    x-swagger-router-controller: tracing
    get:
      summary: Tracing uploads
      tags:
        - Tracings
      responses:
        200:
          description: An array of tracings from SWC file uploads
          schema:
            type: array
            items:
              $ref: '#/definitions/Tracing'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /tracings/{tracingId}:
    x-swagger-router-controller: tracing
    get:
      summary: Tracing definitions
      tags:
        - Tracings
      operationId: getTracingById
      parameters:
        - name: tracingId
          in: path
          description: Tracing object to find
          required: true
          type: string
      responses:
        200:
          description: The tracing
          schema:
            $ref: "#/definitions/Tracing"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /nodes:
    x-swagger-router-controller: tracingNode
    get:
      summary: Tracing nodes
      tags:
        - Nodes
      responses:
        200:
          description: An array of tracing nodes
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /nodes/findByStructure/{structureIdentifierId}:
    x-swagger-router-controller: tracingNode
    get:
      tags:
        - Nodes
      summary: Finds nodes by structure type
      operationId: findByStructure
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: structureIdentifierId
          description: structure id to filter by
          required: true
          type: string
      responses:
        "200":
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'
        "400":
          description: Invalid structure id value
  /nodes/forTracing/{swcTracingId}:
    x-swagger-router-controller: tracing
    get:
      tags:
        - Nodes
        - Tracings
      summary: Finds nodes by tracing
      operationId: forTracing
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: swcTracingId
          description: tracing id to filter by
          required: true
          type: string
      responses:
        "200":
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'
        "400":
          description: Invalid structure id value
  /structures:
    x-swagger-router-controller: structureIdentifier
    get:
      summary: Structure identifier definitions
      tags:
        - Structure Identifiers
      responses:
        200:
          description: An array of structure identifiers
          schema:
            type: array
            items:
              $ref: '#/definitions/StructureIdentifier'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /tracingStructures:
    x-swagger-router-controller: tracingStructure
    get:
      summary: Tracing structure definitions
      tags:
        - Tracings
      responses:
        200:
          description: An array of tracing structures
          schema:
            type: array
            items:
              $ref: '#/definitions/TracingStructure'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /upload:
    # binds a127 app logic to a route
    x-swagger-router-controller: upload
    post:
      summary: Upload file to the database
      # used as the method name of the controller
      tags:
        - Upload
        - Tracings
      consumes:
        - multipart/form-data
      parameters:
        - name: annotator
          in: query
          description: Annotator name
          type: string
        - name: neuronId
          in: query
          description: Neuron Id
          type: string
        - name: tracingStructureId
          in: query
          description: Tracing Structure Id
          type: string
        - name: contents
          in: formData
          description: File to upload
          type: file
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: '#/definitions/TracingPost'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Tracing:
    type: object
    properties:
      id:
        type: string
        description: Internal id
      filename:
        type: string
        description: Original filename
      fileComments:
        type: string
        description: Comments directly in file header
      annotator:
        type: string
        description: Annotator name
      neuronId:
        type: string
        description: Id of neuron in sample database
      tracingStructureId:
        type: string
        description: Id of tracing structure
      xOffset:
        type: number
        format: double
        description: Janelia x offset from SWC file
      yOffset:
        type: number
        format: double
        description: Janelia y offset from SWC file
      zOffset:
        type: number
        format: double
        description: Janelia z offset from SWC file
      createdAt:
        type: string
        format: date-time
        description: Creation time
      updatedAt:
        type: string
        format: date-time
        description: Update time
  TracingPost:
    type: object
    properties:
      filename:
        type: string
        description: Original filename
      annotator:
        type: string
        description: Annotator name
      neuronId:
        type: string
        description: Id of neuron in sample database
      tracingStructureId:
        type: string
        description: Id of tracing structure
  Node:
    type: object
    properties:
      id:
        type: string
        description: Internal id
      createdAt:
        type: string
        format: date-time
        description: Creation time
      updatedAt:
        type: string
        format: date-time
        description: Update time
  StructureIdentifier:
    type: object
    properties:
      id:
        type: string
        description: Internal id
      name:
        type: string
        description: Name
      value:
        type: integer
        description: Enumeration value
      mutable:
        type: boolean
        description: Mutability
      createdAt:
        type: string
        format: date-time
        description: Creation time
      updatedAt:
        type: string
        format: date-time
        description: Update time
  TracingStructure:
    type: object
    properties:
      id:
        type: string
        description: Internal id
      name:
        type: string
        description: Name
      createdAt:
        type: string
        format: date-time
        description: Creation time
      updatedAt:
        type: string
        format: date-time
        description: Update time
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
