swagger: "2.0"
info:
  version: "0.0.1"
  description: "Manage SWC files in the SWC database"
  title: SWC File API
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /samples:
    x-swagger-router-controller: sample
    get:
      summary: Sample definitions
      tags:
        - Samples
      responses:
        200:
          description: An array of files
          schema:
            type: array
            items:
              $ref: '#/definitions/Sample'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /neurons:
    x-swagger-router-controller: neuron
    get:
      summary: Neuron definitions
      tags:
        - Neurons
      responses:
        200:
          description: An array of files
          schema:
            type: array
            items:
              $ref: '#/definitions/Neuron'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /tracings:
    x-swagger-router-controller: tracing
    get:
      summary: Stored tracings from SWC files
      description: |
        The tracings endpoint manages contents of tracings stored in SWC files uploaded and stored in
        raw format on the server.
      tags:
        - Tracings
        - Files
        - Neurons
      responses:
        200:
          description: An array of files
          schema:
            type: array
            items:
              $ref: '#/definitions/Tracing'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /nodes:
    x-swagger-router-controller: tracingNode
    get:
      summary: Stored SWC nodes
      description: |
        The nodes endpoint manages contents of the nodes table.
      tags:
        - Nodes
      responses:
        200:
          description: An array of files
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /nodes/findByStructure/{structure}:
    x-swagger-router-controller: tracingNode
    get:
      tags:
        - Nodes
      summary: Finds nodes by structure type
      operationId: findByStructure
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: structure
          description: structure id to filter by
          required: true
          type: string
      responses:
        "200":
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'
        "400":
          description: Invalid structure id value
  /nodes/forTracing/{tracingId}:
    x-swagger-router-controller: tracingNode
    get:
      tags:
        - Nodes
        - Tracings
      summary: Finds nodes by tracing
      operationId: forTracing
      produces:
        - application/json
        - application/xml
      parameters:
        - in: path
          name: tracingId
          description: tracing id to filter by
          required: true
          type: string
      responses:
        "200":
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Node'
        "400":
          description: Invalid structure id value
  /upload:
    # binds a127 app logic to a route
    x-swagger-router-controller: upload
    post:
      summary: Upload file to the database
      # used as the method name of the controller
      tags:
        - Upload
        - Files
        - Tracings
      consumes:
        - multipart/form-data
      parameters:
        - name: submitter
          in: query
          description: Submitter
          type: string
        - name: tag
          in: query
          description: Submitter
          type: string
        - name: contents
          in: formData
          description: File to upload
          type: file
      responses:
        200:
          description: Success
          schema:
            # a pointer to a definition
            $ref: '#/definitions/Tracing'
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Sample:
    type: object
    properties:
      id:
        type: string
        description: Internal id.
      createdAt:
        type: string
        description: Creation time.
      updatedAt:
        type: string
        description: Update time.
  Neuron:
    type: object
    properties:
      id:
        type: string
        description: Internal id.
      createdAt:
        type: string
        description: Creation time.
      updatedAt:
        type: string
        description: Update time.
  Tracing:
    type: object
    properties:
      id:
        type: string
        description: Internal id.
      filename:
        type: string
        description: Original filename.
      tag:
        type: string
        description: Optional tag.
      submitter:
        type: string
        description: Submitter identification.
      createdAt:
        type: string
        description: Creation time.
      updatedAt:
        type: string
        description: Update time.
  Node:
    type: object
    properties:
      id:
        type: string
        description: Internal id.
      createdAt:
        type: string
        description: Creation time.
      updatedAt:
        type: string
        description: Update time.
  Error: 
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
