version: '2'

services:
  sample-service:
    build: ./sample-service
    environment:
      NODE_ENV: production
    command: node /app/app.js
    ports:
      - 9641:9641
  sample-web:
    build: ./sample-web
    environment:
      NODE_ENV: production
      SAMPLE_SERVICE_PORT: 9641
      SAMPLE_STATUS_PORT: 9642
    command: node /app/dist/server/app.js
    ports:
      - 9643:9643

  tracing-service:
    build: ./swc-service
    environment:
      NODE_ENV: production
    command: node /app/app.js
    ports:
      - 9651:9651
  tracing-web:
    build: ./swc-web
    environment:
      NODE_ENV: production
      SWC_SERVICE_PORT: 9651
      SWC_STATUS_PORT: 9652
      SAMPLE_SERVICE_PORT: 9641
    command: node /app/dist/server/app.js
    ports:
      - 9653:9653

networks:
  default:
    external:
      name: ndb_back_tier
