version: '2'
services:
  sample-datastore:
    image: postgres:latest
    volumes:
      - /sampledbstore
    entrypoint: /bin/bash
  sample-db-server:
    image: postgres:latest
    volumes:
      - ./sample-datastore:/docker-entrypoint-initdb.d
    volumes_from:
      - sample-datastore
    environment:
      POSTGRES_PASSWORD: pgsecret
      PGDATA: /sampledbstore/pgdata
    ports:
      - 5433:5432
  sample-service:
    build: ./sample-service
    environment:
      NODE_ENV: production
    command: node /app/app.js
    ports:
      - 9641:9641
    links:
      - "sample-db-server:sampledatabase"
  sample-status:
    build: ./sample-status
    environment:
      NODE_ENV: production
      SAMPLE_SERVICE_PORT: 9641
    command: node /app/dist/server/app.js
    ports:
      - 9642:9642
    links:
      - "sample-service:sampleservice"
  sample-web:
    build: ./sample-web
    environment:
      NODE_ENV: production
      SAMPLE_SERVICE_PORT: 9641
    command: node /app/dist/server/app.js
    ports:
      - 9643:9643
    links:
      - "sample-service:sampleservice"
      - "sample-status:samplestatus"

