version: '2'
services:
  swc-datastore:
    image: postgres:latest
    volumes:
      - /swcdbstore
    entrypoint: /bin/bash
  swc-db-server:
    image: postgres:latest
    volumes_from:
      - swc-datastore
    environment:
      POSTGRES_PASSWORD: pgsecret
      PGDATA: /swcdbstore/pgdata
    ports:
      - "5432:5432"
  swc-upload:
    build: ./swc-upload
    command: node /app/app.js
    ports:
      - "8080:3000"
    links:
      - swc-db-server:database
    depends_on:
      - swc-db-server
