version: '2'

services:
  sample-service:
    build: ./sample-service
    environment:
      NODE_ENV: test
    command: node /app/app.js
    ports:
      - 8641:9641

  sample-web:
    build: ./sample-web
    environment:
      NODE_ENV: test
      SAMPLE_SERVICE_PORT: 8641
    command: node /app/dist/server/app.js
    ports:
      - 8643:9643

  tracing-service:
    build: ./swc-service
    environment:
      NODE_ENV: test
    command: node /app/app.js
    ports:
      - 8651:9651

  tracing-web:
    build: ./swc-web
    environment:
      NODE_ENV: test
      SWC_SERVICE_PORT: 8651
      SAMPLE_SERVICE_PORT: 8641
    command: node /app/dist/server/app.js
    ports:
      - 8653:9653

networks:
  default:
    external:
      name: ndb_back_tier_test
