swagger: "2.0"
info:
  version: "0.0.1"
  description: "Manage SWC files in the SWC database"
  title: SWC File API
# during dev, should point to your local machine
host: localhost:9651
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /files:
    x-swagger-router-controller: swc-file
    get:
      summary: Stored SWC files
      description: |
        The files endpoint manages contents of SWC files uploaded and stored in
        raw format on the server.
      tags:
        - Files
      responses:
        200:
          description: An array of files
          schema:
            type: array
            items:
              $ref: '#/definitions/SwcFile'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /samples:
    x-swagger-router-controller: swc-sample
    get:
      summary: Stored SWC samples
      description: |
        The samples endpoint manages contents of the samples table.
      tags:
        - Files
      responses:
        200:
          description: An array of files
          schema:
            type: array
            items:
              $ref: '#/definitions/Sample'
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /upload:
    # binds a127 app logic to a route
    x-swagger-router-controller: swc-file
    post:
      description: Uploads a new SWC file to the database
      # used as the method name of the controller
      operationId: upload
      tags:
        - Files
      consumes:
        - multipart/form-data
      parameters:
        - name: contents
          in: formData
          description: File to upload
          type: file
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            type: string
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  SwcFile:
    type: object
    properties:
      id:
        type: integer
        description: Internal id.
      filename:
        type: string
        description: Original filename.
      tag:
        type: string
        description: Optional tag.
      submitter:
        type: string
        description: Submitter identification.
      createdAt:
        type: string
        description: Creation time.
      updatedAt:
        type: string
        description: Update time.
  Sample:
    type: object
    properties:
      id:
        type: integer
        description: Internal id.
      createdAt:
        type: string
        description: Creation time.
      updatedAt:
        type: string
        description: Update time.
  Error: 
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
